title: "Uttiya Pal"
author: "Uttiya Pal"
description: "My personal webpage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", title: "Home" }
  - {file: "about.md", title: "About"}
  - {url: "/files/CV.pdf", title: "CV"}
  - {file: "project.md", title: "Projects"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:iamuttiyapal@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/uttiyapal"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/uttiyapal/"}
  - {title: X, icon: twitter, url: "https://x.com/paluttiya"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/_uttiyaa_/"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/@uttiyapal"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
